#!/bin/bash

# fake gs, usable as a replacement with pdfcrop
# but which uses convert to calculate bounding boxes

# use shopt to find '-f' argument; ignore all others

TEMP=`getopt -q -o f: -n $(basename $0) -- "$@"`
eval set -- "$TEMP"
while true; do case "$1" in

	-f) 	FNAME="$2"
	;;
	esac
	shift || break
done
#echo "FNAME is $FNAME" 1>&2

# following is copied from pdf-reallycrop, shows calculations needed
# to turn convert's output into a gs-style bbox string

convert "$FNAME" -trim -fuzz "10%" -identify /dev/null | while read line; do
	echo "$line" 1>&2
	SED_EXPR="^${FNAME} PDF [0-9]*x[0-9]*=>\([0-9]*x[0-9]*\) \([0-9]*x[0-9]*[-+][0-9]*[-+][0-9]*\) .*"
	GEOMETRY=$( echo "$line" | sed "s~$SED_EXPR~\1~" )
	PAGE_GEOMETRY=$( echo "$line" | sed "s~$SED_EXPR~\2~" )

	if [ -z "$GEOMETRY" ] || [ -z "$PAGE_GEOMETRY" ]; then
		echo "Couldn't get bounding box for file $FNAME" 1>&2
		echo "GEOMETRY is $GEOMETRY, PAGE_GEOMETRY is $PAGE_GEOMETRY" 1>&2
	else
		if [ "$PAGE_GEOMETRY" = "1x1-1-1" ]; then
			XMIN=0; YMIN=0; XMAX=0; YMAX=0
			XMAX
		else
			UNCROPPED_SIZE_X=$( echo $PAGE_GEOMETRY | sed 's/\([0-9]*\)x\([0-9]*\)[-+]\([0-9]*\)[-+]\([0-9]*\).*/\1/')
			UNCROPPED_SIZE_Y=$( echo $PAGE_GEOMETRY | sed 's/\([0-9]*\)x\([0-9]*\)[-+]\([0-9]*\)[-+]\([0-9]*\).*/\2/')
			XMIN=$( echo $PAGE_GEOMETRY             | sed 's/\([0-9]*\)x\([0-9]*\)[-+]\([0-9]*\)[-+]\([0-9]*\).*/\3/')
			YMIN_FROM_BOTTOM=$( echo $PAGE_GEOMETRY | sed 's/\([0-9]*\)x\([0-9]*\)[-+]\([0-9]*\)[-+]\([0-9]*\).*/\4/')
			CROPPED_SIZE_X=$( echo $GEOMETRY | sed 's/\([0-9]*\)x\([0-9]*\).*/\1/')
			CROPPED_SIZE_Y=$( echo $GEOMETRY | sed 's/\([0-9]*\)x\([0-9]*\).*/\2/')
			YMAX=$(( $UNCROPPED_SIZE_Y - $YMIN_FROM_BOTTOM ))
			YMIN=$(( $YMAX - $CROPPED_SIZE_Y ))
			XMAX=$(( $XMIN + $CROPPED_SIZE_X ))
		fi
		echo "%%BoundingBox: $XMIN $YMIN $XMAX $YMAX" 1>&2
		echo "%%HiResBoundingBox: $XMIN.000000 $YMIN.000000 $XMAX.000000 $YMAX.000000" 1>&2
	fi	
done
